switch:
    ethernet:
        address: 192.168.254.100
    raspberry:
        path: '/sys/class/gpio/'
    devices:
        heating_ground_floor:
            id: heating_ground_floor
            name: 'Podłogówka parter'
            type: ethernet
            address: 6
        heating_first_floor:
            id: heating_first_floor
            name: 'Podłogówka piętro'
            type: ethernet
            address: 7
        hot_water_pump:
            id: hot_water_pump
            name: 'Pompa CWU'
            type: ethernet
            address: 3
        light_stairs:
            id: light_stairs
            name: 'Lampa schody'
            type: ethernet
            address: 4
        light_hall:
            id: light_hall
            name: 'Lampa hall'
            type: ethernet
            address: 5
        blind_dinning_up:
            name : 'Roleta jadalnia góra'
            type: raspberry
            pin: 14
            seconds: 29
        blind_dinning_down:
            name : 'Roleta jadalnia dół'
            type: raspberry
            pin: 15
            seconds: 29
sensor:
    w1thermometer:
        base_path: '/sys/bus/w1/devices/'
    devices:
        #outdoor_west:
        #    name: 'Zewnątrz zachód'
        #    type: w1thermometer
        #    address: '28-000002726a7c'
        outdoor_north:
            name: 'Zewnątrz północ'
            type: w1thermometer
            address: '28-00000613e0ac'
        office:
            name: 'Gabinet'
            type: w1thermometer
            address: '28-000004765573'
storing:
    mongo:
        host: 'linus.mongohq.com'
        port: 10080
        user: 'pithermo'
        pass: 'pi2013'
        collection: 'pithermo'

