switch:
    ethernet:
        address: 192.168.254.100
    raspberry:
        path: '/sys/class/gpio/'
    devices:
        heating_ground_floor:
            id: heating_ground_floor
            name: 'Podłogówka parter'
            type: ethernet
            address: 6
        heating_first_floor:
            id: heating_first_floor
            name: 'Podłogówka piętro'
            type: ethernet
            address: 7
        hot_water_pump:
            id: hot_water_pump
            name: 'Pompa CWU'
            type: ethernet
            address: 3
        light_stairs:
            id: light_stairs
            name: 'Lampa schody'
            type: ethernet
            address: 4
        light_hall:
            id: light_hall
            name: 'Lampa hall'
            type: ethernet
            address: 5
        blind_dinning:
            id: blind_dinning
            name: 'Roleta jadalnia'
            type: two_way
            up_pin: 1
            down_pin: 16
            seconds: 22
        blind_terrace:
            id: blind_terrace
            name: 'Roleta taras'
            type: two_way
            up_pin: 4
            down_pin: 5
            seconds: 30
        blind_ground_floor:
            id: blind_ground_floor
            name: 'Roleta parter'
            type: two_way
            aggregate:
                - blind_terrace
                - blind_dinning
        gate_main:
            id: gate_main
            name: 'Brama główna'
            type: click
            pin: 6
        gate_main_door_mode:
            id: gate_main_door_mode
            name: 'Brama furtka'
            type: click_sequence
            sequence:
                - switch: gate_main
                  pin: 6
                  execute_after: 0
                - switch: gate_main
                  pin: 6
                  execute_after: 2
                - switch: gate_main
                  pin: 6
                  execute_after: 120
        gate_garage:
            id: gate_garage
            name: 'Brama garaż'
            type: click
            pin: 11
sensor:
    w1thermometer:
        base_path: '/sys/bus/w1/devices/'
    devices:
        #outdoor_west:
        #    name: 'Zewnątrz zachód'
        #    type: w1thermometer
        #    address: '28-000002726a7c'
        outdoor_east:
            name: 'Zewnątrz'
            type: w1thermometer
            address: '28-000002726a7c'
        basement:
            name: 'Piwnica'
            type: w1thermometer
            address: '28-000004765573'
        entrance:
            name: 'Wiatrołap'
            type: w1thermometer
            address: '28-00000594a06c'
        kitchen:
            name: 'Kuchnia'
            type: w1thermometer
            address: '28-000005caf175'
        garage:
            name: 'Garaż'
            type: w1thermometer
            address: '28-000006142545'
storing:
    mongo:
        host: 'linus.mongohq.com'
        port: 10080
        user: 'pithermo'
        pass: 'pi2013'
        collection: 'pithermo'
